repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0 # Use the latest release version from the repo.
  hooks:
  - id: terraform_fmt
    files: ^terraform/.*\.tf$
- repo: https://github.com/anderseknert/pre-commit-opa
  rev: v1.4.1
  hooks:
  - id: opa-fmt
  - id: opa-check
