name: Terraform
on:
  - push
  - workflow_dispatch

permissions:
  id-token: write

env:
  ARM_USE_OIDC: true
  ARM_USE_AZUREAD: true
  ARM_TENANT_ID: ${{ secrets.azure_tenant_id }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.azure_subscription_id }}
  ARM_CLIENT_ID: ${{ secrets.azure_client_id }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Az CLI login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.azure_client_id }}
        tenant-id: ${{ secrets.azure_tenant_id }}
        subscription-id: ${{ secrets.azure_subscription_id }}
    - name: Install Conftest
      run: |
        wget -O conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/download/v0.28.0/conftest_0.28.0_Linux_x86_64.tar.gz
        tar xzf conftest.tar.gz
        sudo mv conftest /usr/local/bin/
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init
    - name: Terraform Validate
      working-directory: ./terraform
      run: terraform validate
    - name: Terraform Plan tests
      working-directory: ./terraform
      run: |
        terraform plan -out=tfplan
        terraform-bin show -json -no-color tfplan > tfplan.json
        cat tfplan.json
        cat tfplan.json >> $GITHUB_STEP_SUMMARY
#        conftest test --policy ../policy/* tfplan.json
    - name: Conftest Action
      uses: YubicoLabs/action-conftest@v3
      with:
#        policy: policy/main.rego
        files: ./terraform/tfplan.json
#    - name: Terraform Apply
#      working-directory: ./terraform
#      run: terraform apply tfplan
