name: Terraform
on:
  - push
  - workflow_dispatch

permissions:
  id-token: write

env:
  ARM_USE_OIDC: true
  ARM_USE_AZUREAD: true
  ARM_TENANT_ID: ${{ secrets.azure_tenant_id }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.azure_subscription_id }}
  ARM_CLIENT_ID: ${{ secrets.azure_client_id }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Az CLI login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.azure_client_id }}
        tenant-id: ${{ secrets.azure_tenant_id }}
        subscription-id: ${{ secrets.azure_subscription_id }}
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init
    - name: Terraform Validate
      working-directory: ./terraform
      run: terraform validate
    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan -out=tfplan
    - name: Convert plan to JSON
      id: terraform-plan-json
      working-directory: ./terraform
      run: terraform show -json tfplan > plan.json
    - name: Add plan to summary
      working-directory: ./terraform
      run: terraform-bin show -json -no-color tfplan >> $GITHUB_STEP_SUMMARY
    - name: Install Conftest
      run: |
        wget -O conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/download/v0.28.0/conftest_0.28.0_Linux_x86_64.tar.gz
        tar xzf conftest.tar.gz
        sudo mv conftest /usr/local/bin/
    - name: Conftest Test
      working-directory: ./terraform
      run: conftest test plan.json
#    - name: Conftest Action
#      uses: YubicoLabs/action-conftest@v3
#      env:
#        POLICY_PATH: ./policy
#        PLAN_PATH: ./tfplan.json
#      with:
#        files: tfplan.json
#    - name: Terraform Apply
#      working-directory: ./terraform
#      run: terraform apply tfplan
